language: python
matrix:
  include:
  - name: Python 3.7 on Windows
      os: windows
      language: shell
      before_install: choco install python && pip install Flask
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install: python setup.py install
      script: python unittest_api.py