language: python
python:
  - "3.7"
  - "2.7"

stage:
  - dev
  - prod

jobs:
  include:
    - stage: dev
      name: test1
      python: 3.7
      script: echo "hello world from dev11 3.7"

    - name: test2
      script: echo "hello world from dev22 2.7"
      python: 2.7


    - stage: prod
      name: test1
      python: 3.7
      script: echo "hello world from prod11 3.7"

    - script: echo "hello world from prod22"
      python: 2.7
      name: test2