
language: python
python:
  - "3.7"
  - "2.7"
cache: pip
install: "pip install -r requirement.txt"

stage:
  - dev
  - prod


jobs:
  include:
    - stage: dev
      script: python unittest_api.py
      name: test2

    - stage: prod
      name: test1
      script: echo "hello world from prod"